// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp3rWw6262OB8EzNsc6njtwiaJzoXhIXM',
    appId: '1:625310299583:web:f4e0f5b8a07b595d57dd0a',
    messagingSenderId: '625310299583',
    projectId: 'flutterdb-1a2a7',
    authDomain: 'flutterdb-1a2a7.firebaseapp.com',
    storageBucket: 'flutterdb-1a2a7.appspot.com',
    measurementId: 'G-Q6B8H196DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC36_6GMvkpinY3YMvlxuPQi8Fvogk5hoo',
    appId: '1:625310299583:android:a96427e5ce98bf3857dd0a',
    messagingSenderId: '625310299583',
    projectId: 'flutterdb-1a2a7',
    storageBucket: 'flutterdb-1a2a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3FAwBidYxSr52oX4h4BuAbBjxJoGKGxE',
    appId: '1:625310299583:ios:b95eb7063cd9ff2257dd0a',
    messagingSenderId: '625310299583',
    projectId: 'flutterdb-1a2a7',
    storageBucket: 'flutterdb-1a2a7.appspot.com',
    androidClientId: '625310299583-cdvu044rep5rcfid18fe9ubs31j4bi5l.apps.googleusercontent.com',
    iosClientId: '625310299583-bmgo9l3gmik6o3uasso4sn41piuiabt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseIntegrate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3FAwBidYxSr52oX4h4BuAbBjxJoGKGxE',
    appId: '1:625310299583:ios:c1680050141376bd57dd0a',
    messagingSenderId: '625310299583',
    projectId: 'flutterdb-1a2a7',
    storageBucket: 'flutterdb-1a2a7.appspot.com',
    androidClientId: '625310299583-cdvu044rep5rcfid18fe9ubs31j4bi5l.apps.googleusercontent.com',
    iosClientId: '625310299583-lhudr8v7oshph5mq5tb6fi5d2nrp4eer.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseIntegrate.RunnerTests',
  );
}
